'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Example 3:

Input: s = "a", t = "aa"
Output: "a"
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        #Solution 1
        for i in t:
            if t.count(i) != s.count(i):
                return i


        #Solution2
        hashMapS = {}
        hashMapT = {}

        for char in s:
            hashMapS[char] = 1+ hashMapS.get(char, 0)

        for char in t:
            hashMapT[char] = 1 + hashMapT.get(char, 0)
        
        for c in hashMapT:
            if c not in hashMapS:
                return c
            if hashMapS[c] < hashMapT[c]:
                return c

        #Solution 3
        sum_s, sum_t = 0, 0
        for c in s:
            sum_s += ord(c)
        for c in t:
            sum_t += ord(c)
        
        return chr(sum_t - sum_s)

'''
Success
Details 
Runtime: 32 ms, faster than 82.72% of Python3 online submissions for Find the Difference.
Memory Usage: 14.2 MB, less than 82.85% of Python3 online submissions for Find the Difference.
'''